apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator
  namespace: metal3
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /baremetal-operator
        args:
        - --enable-leader-election
        image: quay.io/metal3-io/baremetal-operator
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: ironic
        name: manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 3
          periodSeconds: 3
      terminationGracePeriodSeconds: 10
