apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-controller-manager
  namespace: baremetal-operator-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: IfNotPresent