apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator
  namespace: metal3
spec:
  template:
    spec:
      containers:
      - name: ironic-proxy
        image: alpine/socat
        command: ["/bin/sh", "-c"]
        args:
        - socat tcp-listen:6385,fork,reuseaddr tcp-connect:$PROVISIONING_IP:6385
        imagePullPolicy: Always
      - name: ironic-inspector-proxy
        image: alpine/socat
        command: ["/bin/sh", "-c"]
        args:
        - socat tcp-listen:5050,fork,reuseaddr tcp-connect:$PROVISIONING_IP:5050
        imagePullPolicy: Always
